stages:
    - deploy
    - notify
    - cleanup

deploy:
    stage: deploy
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
    tags:
        - docker-prod
    script:
        - echo "開始零停機部署, now deploying..."
        - cd $CI_PROJECT_DIR
        - chmod +x deploy.sh
        - ./deploy.sh
        - echo "零停機部署完成, deploy job's done"

# 自動清理 Docker Image
cleanup:
    stage: cleanup
    tags:
        - docker-prod
    script:
        - echo "Now cleanup Docker images"
        - sudo docker container prune -f
        - sudo docker image prune -af
        - sudo docker volume prune -f
        - sudo docker system prune -af --volumes
        - echo "Clearing Docker images done"
    when: always
    allow_failure: true
