version: '3.8'

services:
    eip-ui-v2-blue:
        build: .
        container_name: eip-ui-v2-blue
        image: eip-ui-v2:blue
        expose:
            - '3000'
        environment:
            - NODE_ENV=dev
            - TZ=Asia/Ho_Chi_Minh
            - NEXT_TELEMETRY_DISABLED=1
        restart: always
        networks:
            - EipApps_network
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:3000/api/health',
                ]
            interval: 20s
            timeout: 5s
            retries: 5
            start_period: 120s

    eip-ui-v2-green:
        build: .
        container_name: eip-ui-v2-green
        image: eip-ui-v2:green
        expose:
            - '3000'
        environment:
            - NODE_ENV=dev
            - TZ=Asia/Ho_Chi_Minh
            - NEXT_TELEMETRY_DISABLED=1
        restart: always # 永遠自動重啟
        networks:
            - EipApps_network
        healthcheck:
            test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000']
            interval: 20s
            timeout: 5s
            retries: 5
            start_period: 240s

    nginx:
        image: nginx:1.25-alpine
        container_name: eip-ui-proxy
        ports:
            - '80:80'
        volumes:
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - eip-ui-v2-blue
            - eip-ui-v2-green
        networks:
            - EipApps_network

networks:
    EipApps_network:
        external: true
