version: '3.8'

services:
  blue:
    build: .
    container_name: eip-ui-blue
    image: eip-ui:blue
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
      - NEXT_TELEMETRY_DISABLED=1
    restart: always
    networks:
      - EipApps_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 240s

  green:
    build: .
    container_name: eip-ui-green
    image: eip-ui:green
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Ho_Chi_Minh
      - NEXT_TELEMETRY_DISABLED=1
    restart: always
    networks:
      - EipApps_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 240s

  nginx:
    image: nginx:1.25-alpine
    container_name: eip-ui-proxy
    ports:
      - "8888:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - blue
      - green
    networks:
      - EipApps_network

networks:
  EipApps_network:
    external: true