'use client';

import { GenericTable } from '@/components/common/GenericTable';
import { DataType, workdayCols } from '@/utils/constants/cols/workdayCols';

function Workday() {
    const data: DataType[] = [
        {
            key: '1',
            stt: 1,
            cardNumber: 'EMP001',
            fullName: 'Nguyễn Văn A',
            unit: 'IT',
            shift: 'Ca 1',
            date: '2024-03-20',
            week: 'T4',
            t1: '08:00',
            t2: '17:00',
            log: 'Normal',
            abnormal: '',
            GC: '8',
            NLE: '',
            _150: '',
            _200: '',
            _300: '',
            _390: '',
            _400: '',
            A: '',
            KP: '',
            B: '',
            C: '',
            D: '',
            DT: '',
            VS: '',
            GDem: '',
            G200: '',
            G210: '',
            Tcom: '',
            CTMTCN: '',
            VPSX: '',
            PNTrua: '1',
            PNTca: '',
        },
        {
            key: '2',
            stt: 2,
            cardNumber: 'EMP002',
            fullName: 'Trần Thị B',
            unit: 'HR',
            shift: 'Ca 2',
            date: '2024-03-20',
            week: 'T4',
            t1: '14:00',
            t2: '22:00',
            log: 'OT',
            abnormal: '',
            GC: '8',
            NLE: '2',
            _150: '2',
            _200: '',
            _300: '',
            _390: '',
            _400: '',
            A: '',
            KP: '',
            B: '',
            C: '',
            D: '',
            DT: '',
            VS: '',
            GDem: '',
            G200: '',
            G210: '',
            Tcom: '',
            CTMTCN: '',
            VPSX: '',
            PNTrua: '1',
            PNTca: '',
        },
        {
            key: '3',
            stt: 3,
            cardNumber: 'EMP003',
            fullName: 'Lê Văn C',
            unit: 'Production',
            shift: 'Ca 3',
            date: '2024-03-20',
            week: 'T4',
            t1: '22:00',
            t2: '06:00',
            log: 'Night Shift',
            abnormal: '',
            GC: '8',
            NLE: '',
            _150: '',
            _200: '',
            _300: '',
            _390: '',
            _400: '',
            A: '',
            KP: '',
            B: '',
            C: '',
            D: '',
            DT: '',
            VS: '',
            GDem: '8',
            G200: '',
            G210: '',
            Tcom: '',
            CTMTCN: '',
            VPSX: '',
            PNTrua: '1',
            PNTca: '',
        },
    ];

    return (
        <div className="min-h-screen">
            <div className="h-[100px] bg-amber-50 mb-2">actions</div>
            <GenericTable<DataType> columns={workdayCols} dataSource={data} rowKey="key" />
        </div>
    );
}

export default Workday;
