export const urls = {
    login: '/auth/signin',
    IT: 'IT',
    logs: 'logs',
    user_operation: 'user_operation',
    user: 'user',
    account: 'account',
    roles: 'roles',
    password: 'password',
    cache: 'cache',
    work_place: 'work_place',
    hr: 'hr',
    attendance: 'attendance',
    summary: 'summary',
    summary_v2: 'summary_v2',
    dept_unit: 'dept_unit',
    organization: 'organization',
    unit_category: 'unit_category',
    unit_type: 'unit_type',
    jobtitle: 'jobtitle',
    nation: 'nation',
};
